---
- name: Configure NTP server in all Client machine
  hosts: all
  gather_facts: true
  tasks:
    - name: Install NTP and other service in Alma linux
      yum:
        name: "{{item}}"
        state: latest
      when: ansible_distribution == "AlmaLinux"
      loop:
        - chrony
        - wget
        - git
        - zip

    - name: Install NTP and ather service in Ubuntu
      apt:
        name: "{{item}}"
        state: latest
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - git
        - zip
        - wget

    - name: Start and enable service in Alma Linux
      service: 
        name: chronyd
        state: started
        enabled: yes 
      when: ansible_distribution == "AlmaLinux"

    - name: Start and enable service in Ubuntu 
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Deploy NTP configuration in Ubuntu using Template module
      template:
        src: template/ntp_ubuntu
        dest: /etc/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
      notify:
        - restart ntp

    - name: Deploy NTP configuration in AlmaLinux using Template module
      template:
        src: template/ntp_alma
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "AlmaLinux"
      notify:
        - restart chronyd

  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted
      when: ansible_distribution == "Ubuntu"

    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
      when: ansible_distribution == "AlmaLinux"
