---
- name: Playbook to fetch server informations using setup modules
  hosts: all
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution

    - name: Print OS family
      debug:
        var: ansible_os_family

    - name: Print the Free RAM memory
      debug: 
        var: ansible_memory_mb.real.free 
    - name: Print tbe used RAM memory
      debug:
        var: ansible_memory_mb.real.used
